steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/cloudbuild-k', '.']
- # Verify kustomize has been built correctly
  name: 'gcr.io/$PROJECT_ID/cloudbuild-k'
  entrypoint: 'kustomize'
  args: ['version']

images: ['gcr.io/$PROJECT_ID/cloudbuild-k']
